config/routes.rb
Consejocomunal::Application.routes.draw do
  resources :habitantes

end

app/models/habitante.rb
class Habitante < ActiveRecord::Base
  attr_accessible :avenida, :calle, :cedula, :manzana_id, :nombre, :telefono

  def nuevo

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/habitantes_controller.rb
class HabitantesController < ApplicationController
  # GET /habitantes
  # GET /habitantes.json
  def index
    @habitantes = Habitante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @habitantes }
    end
  end

  # GET /habitantes/1
  # GET /habitantes/1.json
  def show
    @habitante = Habitante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @habitante }
    end
  end

  # GET /habitantes/new
  # GET /habitantes/new.json
  def new
    @habitante = Habitante.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @habitante }
    end
  end

  # GET /habitantes/1/edit
  def edit
    @habitante = Habitante.find(params[:id])
  end

  # POST /habitantes
  # POST /habitantes.json
  def create
    @habitante = Habitante.new(params[:habitante])

    respond_to do |format|
      if @habitante.save
        format.html { redirect_to @habitante, notice: 'Habitante was successfully created.' }
        format.json { render json: @habitante, status: :created, location: @habitante }
      else
        format.html { render action: "new" }
        format.json { render json: @habitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /habitantes/1
  # PUT /habitantes/1.json
  def update
    @habitante = Habitante.find(params[:id])

    respond_to do |format|
      if @habitante.update_attributes(params[:habitante])
        format.html { redirect_to @habitante, notice: 'Habitante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @habitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habitantes/1
  # DELETE /habitantes/1.json
  def destroy
    @habitante = Habitante.find(params[:id])
    @habitante.destroy

    respond_to do |format|
      format.html { redirect_to habitantes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habitantes_helper.rb
module HabitantesHelper
end

app/views/habitantes/_form.html.erb
<%= form_for(@habitante) do |f| %>
  <% if @habitante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@habitante.errors.count, "Errores.") %> Los siguientes errores no permitieron Guardar:</h2>

      <ul>
      <% @habitante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cedula %><br />
    <%= f.text_field :cedula, class: "span2"  %>
  </div>
  <div class="field">
    <%= f.label :nombre, "Nombre y apellido"%><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label "Manzana." %><br />
    <%= f.text_field :manzana_id, class: "span2"  %>
  </div>
  <div class="field">
    <%= f.label :calle %><br />
    <%= f.text_field :calle, class: "span2" %>
  </div>
  <div class="field">
    <%= f.label :avenida %><br />
    <%= f.text_field :avenida, class: "span1" %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/habitantes/edit.html.erb
<h1>Editing habitante</h1>

<div class="span6 offset3">
  <%= render 'form' %>
</div>

<%= link_to 'Mostrar', @habitante %> |
<%= link_to 'Volver', habitantes_path %>

app/views/habitantes/index.html.erb
<div class="row-fluid">
    <div class="span9">
        <h1>Lista de habitantes</h1>

        <table class="table table-striped span9">
          <tr>
            <th>Cedula</th>
            <th>Nombre</th>
            <th>Manzana</th>
            <th>Calle</th>
            <th>Avenida</th>
            <th>Telefono</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

        <% @habitantes.each do |habitante| %>
          <tr>
            <td><%= habitante.cedula %></td>
            <td><%= habitante.nombre %></td>
            <td><%= habitante.manzana_id %></td>
            <td><%= habitante.calle %></td>
            <td><%= habitante.avenida %></td>
            <td><%= habitante.telefono %></td>
            <td><%= link_to 'Ver', habitante, class: "btn btn-info" %></td>
            <td><%= link_to 'Editar', edit_habitante_path(habitante), class: "btn btn-warning" %></td>
            <td><%= link_to 'Borrar', habitante, method: :delete, data: { confirm: 'Estas seguro/a?' }, 
                    class: "btn btn-danger" %></td>
          </tr>
        <% end %>
        </table>

        <br />

        <%= link_to 'Nuevo Habitante', new_habitante_path %>
    </div>
</div>

app/views/habitantes/new.html.erb
<h1>Nuevo habitante</h1>

<div class="span6 offset3">
  <%= render 'form' %>
</div>

<%= link_to 'Back', habitantes_path %>

app/views/habitantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cedula:</b>
  <%= @habitante.cedula %>
</p>

<p>
  <b>Nombre:</b>
  <%= @habitante.nombre %>
</p>

<p>
  <b>Manzana:</b>
  <%= @habitante.manzana_id %>
</p>

<p>
  <b>Calle:</b>
  <%= @habitante.calle %>
</p>

<p>
  <b>Avenida:</b>
  <%= @habitante.avenida %>
</p>

<p>
  <b>Telefono:</b>
  <%= @habitante.telefono %>
</p>


<%= link_to 'Edit', edit_habitante_path(@habitante) %> |
<%= link_to 'Back', habitantes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consejocomunal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>